[package]
name = "pixels-16"
version = "0.1.0"
authors = ["Spencer Elliott <s.elliott123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.0.2"
winit = "0.21.0"
winit_input_helper = "0.5.0"
